apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  namespace: turbine
  labels:
   app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      namespace: turbine
      labels:
        app: node-web-app
    spec:
      imagePullSecrets:
        - name: az-sedockerreg
      containers:
      - name: node-web-app
        image: secontainer.azurecr.io/node-web-app:latest
        ports:
          - containerPort: 8080
      restartPolicy: Always